// Generated by CoffeeScript 1.9.3
(function() {
  var hammertime;

  hammertime = new Hammer($(".phrases-window")[0]);

  hammertime.on("pan", function(ev) {
    var base;
    base = $(window).scrollTop();
    $(window).scrollTop(base + ev.deltaY / -10.0);
    return console.log(ev);
  });

}).call(this);
